---
# The Markdown Toolkit (MDTK) is released under the Creative Commons Attribution 4.0 International (CC BY 4.0) license.
# https://creativecommons.org/licenses/by/4.0/
#
# Do not use staging links.
#
extends: existence
message: "Do not use staging links in CoreWeave documentation."
link: https://github.com/dfinster/MDTK
level: error
nonword: true
scope: raw
tokens:
  - '//cloud.staging.coreweave.com/'
